# Generated by Django 3.1 on 2020-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dataExpiracao', models.DateField()),
                ('dataUso', models.DateField(editable=False, null=True)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Expirado', 'Expirado'), ('Utilizado', 'Utilizado')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
